# res://addons/godot-stat-math/tables/cdf_pdf_integration_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY
# Generated with: scipy 1.15.3, numpy 2.3.0

## Integration test data for CDF/PDF derivative relationships, monotonicity testing,
## cross-function consistency, and boundary behavior validation.
##
## All expected values are calculated using scipy statistical functions to ensure
## mathematical accuracy and consistency across test scenarios.

const VALUES: Dictionary = {
	"normal_derivative_tests": [  # Generated using: stats.norm.cdf(x, mu, sigma) and stats.norm.pdf(x, mu, sigma)
		{ "params": [0.0, 0.0, 1.0], "cdf_expected": 0.50000000, "pdf_expected": 0.39894228 },
		{ "params": [1.0, 0.0, 1.0], "cdf_expected": 0.84134475, "pdf_expected": 0.24197072 },
		{ "params": [-1.0, 0.0, 1.0], "cdf_expected": 0.15865525, "pdf_expected": 0.24197072 },
		{ "params": [2.0, 0.0, 1.0], "cdf_expected": 0.97724987, "pdf_expected": 0.05399097 },
		{ "params": [-2.0, 0.0, 1.0], "cdf_expected": 0.02275013, "pdf_expected": 0.05399097 },
	],
	"exponential_derivative_tests": [  # Generated using: stats.expon.cdf(x, scale=1/lambda) and stats.expon.pdf(x, scale=1/lambda)
		{ "params": [0.1, 2.0], "cdf_expected": 0.18126925, "pdf_expected": 1.63746151 },
		{ "params": [0.5, 2.0], "cdf_expected": 0.63212056, "pdf_expected": 0.73575888 },
		{ "params": [1.0, 2.0], "cdf_expected": 0.86466472, "pdf_expected": 0.27067057 },
		{ "params": [2.0, 2.0], "cdf_expected": 0.98168436, "pdf_expected": 0.03663128 },
		{ "params": [5.0, 2.0], "cdf_expected": 0.99995460, "pdf_expected": 0.00009080 },
	],
	"uniform_derivative_tests": [  # Generated using: stats.uniform.cdf(x, a, b-a) and stats.uniform.pdf(x, a, b-a)
		{ "params": [1.5, 1.0, 4.0], "cdf_expected": 0.16666667, "pdf_expected": 0.33333333 },
		{ "params": [2.0, 1.0, 4.0], "cdf_expected": 0.33333333, "pdf_expected": 0.33333333 },
		{ "params": [2.5, 1.0, 4.0], "cdf_expected": 0.50000000, "pdf_expected": 0.33333333 },
		{ "params": [3.0, 1.0, 4.0], "cdf_expected": 0.66666667, "pdf_expected": 0.33333333 },
		{ "params": [3.5, 1.0, 4.0], "cdf_expected": 0.83333333, "pdf_expected": 0.33333333 },
	],
	"beta_derivative_tests": [  # Generated using: stats.beta.cdf(x, alpha, beta) and stats.beta.pdf(x, alpha, beta)
		{ "params": [0.1, 2.0, 3.0], "cdf_expected": 0.05230000, "pdf_expected": 0.97200000 },
		{ "params": [0.3, 2.0, 3.0], "cdf_expected": 0.34830000, "pdf_expected": 1.76400000 },
		{ "params": [0.5, 2.0, 3.0], "cdf_expected": 0.68750000, "pdf_expected": 1.50000000 },
		{ "params": [0.7, 2.0, 3.0], "cdf_expected": 0.91630000, "pdf_expected": 0.75600000 },
		{ "params": [0.9, 2.0, 3.0], "cdf_expected": 0.99630000, "pdf_expected": 0.10800000 },
	],
	"weibull_derivative_tests": [  # Generated using: stats.weibull_min.cdf(x, c=shape, scale=scale) and stats.weibull_min.pdf(x, c=shape, scale=scale)
		{ "params": [0.5, 2.0, 2.0], "cdf_expected": 0.06058694, "pdf_expected": 0.23485327 },
		{ "params": [1.0, 2.0, 2.0], "cdf_expected": 0.22119922, "pdf_expected": 0.38940039 },
		{ "params": [1.5, 2.0, 2.0], "cdf_expected": 0.43021718, "pdf_expected": 0.42733712 },
		{ "params": [2.0, 2.0, 2.0], "cdf_expected": 0.63212056, "pdf_expected": 0.36787944 },
		{ "params": [3.0, 2.0, 2.0], "cdf_expected": 0.89460078, "pdf_expected": 0.15809884 },
	],
	"normal_monotonicity": [  # Generated using: stats.norm.cdf(x, mu, sigma)
		{ "params": [-3.0, 0.0, 1.0], "expected": 0.00134990 },
		{ "params": [-1.0, 0.0, 1.0], "expected": 0.15865525 },
		{ "params": [0.0, 0.0, 1.0], "expected": 0.50000000 },
		{ "params": [1.0, 0.0, 1.0], "expected": 0.84134475 },
		{ "params": [3.0, 0.0, 1.0], "expected": 0.99865010 },
	],
	"exponential_monotonicity": [  # Generated using: stats.expon.cdf(x, scale=1/lambda)
		{ "params": [0.1, 1.0], "expected": 0.09516258 },
		{ "params": [0.5, 1.0], "expected": 0.39346934 },
		{ "params": [1.0, 1.0], "expected": 0.63212056 },
		{ "params": [2.0, 1.0], "expected": 0.86466472 },
		{ "params": [5.0, 1.0], "expected": 0.99326205 },
	],
	"uniform_monotonicity": [  # Generated using: stats.uniform.cdf(x, a, b-a)
		{ "params": [1.0, 1.0, 4.0], "expected": 0.00000000 },
		{ "params": [1.5, 1.0, 4.0], "expected": 0.16666667 },
		{ "params": [2.5, 1.0, 4.0], "expected": 0.50000000 },
		{ "params": [3.5, 1.0, 4.0], "expected": 0.83333333 },
		{ "params": [4.0, 1.0, 4.0], "expected": 1.00000000 },
	],
	"beta_monotonicity": [  # Generated using: stats.beta.cdf(x, alpha, beta)
		{ "params": [0.0, 2.0, 3.0], "expected": 0.00000000 },
		{ "params": [0.25, 2.0, 3.0], "expected": 0.26171875 },
		{ "params": [0.5, 2.0, 3.0], "expected": 0.68750000 },
		{ "params": [0.75, 2.0, 3.0], "expected": 0.94921875 },
		{ "params": [1.0, 2.0, 3.0], "expected": 1.00000000 },
	],
	"gamma_monotonicity": [  # Generated using: stats.gamma.cdf(x, a=shape, scale=scale)
		{ "params": [0.1, 2.0, 1.5], "expected": 0.00212588 },
		{ "params": [1.0, 2.0, 1.5], "expected": 0.14430480 },
		{ "params": [2.0, 2.0, 1.5], "expected": 0.38494001 },
		{ "params": [4.0, 2.0, 1.5], "expected": 0.74522735 },
		{ "params": [6.0, 2.0, 1.5], "expected": 0.90842181 },
	],
	"weibull_monotonicity": [  # Generated using: stats.weibull_min.cdf(x, c=shape, scale=scale)
		{ "params": [0.1, 2.0, 2.0], "expected": 0.00249688 },
		{ "params": [1.0, 2.0, 2.0], "expected": 0.22119922 },
		{ "params": [2.0, 2.0, 2.0], "expected": 0.63212056 },
		{ "params": [3.0, 2.0, 2.0], "expected": 0.89460078 },
		{ "params": [4.0, 2.0, 2.0], "expected": 0.98168436 },
	],
	"normal_cdf_ppf_consistency": [  # Generated using: stats.norm.cdf(x, mu, sigma) and stats.norm.ppf(p, mu, sigma)
		{ "cdf_params": [1.5, 0.0, 1.0], "cdf_expected": 0.93319280, "ppf_expected": 1.50000000 },
		{ "cdf_params": [0.0, 0.0, 1.0], "cdf_expected": 0.50000000, "ppf_expected": 0.00000000 },
		{ "cdf_params": [-1.5, 0.0, 1.0], "cdf_expected": 0.06680720, "ppf_expected": -1.50000000 },
	],
	"exponential_cdf_ppf_consistency": [  # Generated using: stats.expon.cdf(x, scale=1/lambda) and stats.expon.ppf(p, scale=1/lambda)
		{ "cdf_params": [2.0, 1.0], "cdf_expected": 0.86466472, "ppf_expected": 2.00000000 },
		{ "cdf_params": [1.0, 1.0], "cdf_expected": 0.63212056, "ppf_expected": 1.00000000 },
		{ "cdf_params": [0.5, 1.0], "cdf_expected": 0.39346934, "ppf_expected": 0.50000000 },
	],
	"uniform_cdf_ppf_consistency": [  # Generated using: stats.uniform.cdf(x, a, b-a) and stats.uniform.ppf(p, a, b-a)
		{ "cdf_params": [2.5, 1.0, 4.0], "cdf_expected": 0.50000000, "ppf_expected": 2.50000000 },
		{ "cdf_params": [1.5, 1.0, 4.0], "cdf_expected": 0.16666667, "ppf_expected": 1.50000000 },
		{ "cdf_params": [3.5, 1.0, 4.0], "cdf_expected": 0.83333333, "ppf_expected": 3.50000000 },
	],
	"normal_boundary_tests": [  # Generated using: stats.norm.cdf(x, mu, sigma) and stats.norm.pdf(x, mu, sigma)
		{ "params": [0.0, 0.0, 1.0], "cdf_expected": 0.50000000, "pdf_expected": 0.39894228 },
		{ "params": [10.0, 0.0, 1.0], "cdf_expected": 1.00000000, "pdf_expected": 0.00000000 },
		{ "params": [-10.0, 0.0, 1.0], "cdf_expected": 0.00000000, "pdf_expected": 0.00000000 },
	],
	"uniform_boundary_tests": [  # Generated using: stats.uniform.cdf(x, a, b-a) and stats.uniform.pdf(x, a, b-a)
		{ "params": [1.0, 1.0, 4.0], "cdf_expected": 0.00000000, "pdf_expected": 0.33333333 },
		{ "params": [4.0, 1.0, 4.0], "cdf_expected": 1.00000000, "pdf_expected": 0.33333333 },
		{ "params": [0.5, 1.0, 4.0], "cdf_expected": 0.00000000, "pdf_expected": 0.00000000 },
		{ "params": [4.5, 1.0, 4.0], "cdf_expected": 1.00000000, "pdf_expected": 0.00000000 },
	],
	"beta_boundary_tests": [  # Generated using: stats.beta.cdf(x, alpha, beta) and stats.beta.pdf(x, alpha, beta)
		{ "params": [0.0, 2.0, 3.0], "cdf_expected": 0.00000000, "pdf_expected": 0.00000000 },
		{ "params": [1.0, 2.0, 3.0], "cdf_expected": 1.00000000, "pdf_expected": 0.00000000 },
	],
	"exponential_boundary_tests": [  # Generated using: stats.expon.cdf(x, scale=1/lambda) and stats.expon.pdf(x, scale=1/lambda)
		{ "params": [0.0, 2.0], "cdf_expected": 0.00000000, "pdf_expected": 2.00000000 },
	],
}