# res://addons/godot-stat-math/tables/cdf_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"normal_cdf": [  # Generated using: stats.norm.cdf(x, mu, sigma)
		{ "params": [1.96, 0.0, 1.0], "expected": 0.97500210 },
		{ "params": [-1.96, 0.0, 1.0], "expected": 0.02499790 },
		{ "params": [0.0, 0.0, 1.0], "expected": 0.50000000 },
		{ "params": [2.0, 2.0, 1.0], "expected": 0.50000000 },
		{ "params": [0.0, 2.0, 0.5], "expected": 0.00003167 },
	],
	"exponential_cdf": [  # Generated using: stats.expon.cdf(x, scale=1.0/lambda)
		{ "params": [2.0, 2.0], "expected": 0.98168436 },
		{ "params": [1.0, 1.0], "expected": 0.63212056 },
		{ "params": [0.693147, 1.0], "expected": 0.49999991 },
	],
	"gamma_cdf": [  # Generated using: stats.gamma.cdf(x, a=shape, scale=scale)
		{ "params": [2.0, 2.0, 1.0], "expected": 0.59399415 },
		{ "params": [1.0, 1.0, 1.0], "expected": 0.63212056 },
		{ "params": [3.841, 1.0, 1.0], "expected": 0.97852788 },
	],
	"beta_cdf": [  # Generated using: stats.beta.cdf(x, alpha, beta)
		{ "params": [0.5, 2.0, 2.0], "expected": 0.50000000 },
		{ "params": [0.25, 2.0, 3.0], "expected": 0.26171875 },
		{ "params": [0.75, 3.0, 2.0], "expected": 0.73828125 },
	],
	"chi_square_cdf": [  # Generated using: stats.chi2.cdf(x, df)
		{ "params": [3.841, 1.0], "expected": 0.94998632 },
		{ "params": [5.991, 2.0], "expected": 0.94998838 },
		{ "params": [7.815, 3.0], "expected": 0.95000610 },
	],
	"weibull_cdf": [  # Generated using: stats.weibull_min.cdf(x, c=shape, scale=scale)
		{ "params": [1.5, 1.0, 2.0], "expected": 0.89460078 },
		{ "params": [2.0, 2.0, 2.0], "expected": 0.63212056 },
		{ "params": [0.5, 1.0, 1.0], "expected": 0.39346934 },
	],
	"t_cdf": [  # Generated using: stats.t.cdf(x, df)
		{ "params": [1.0, 10.0], "expected": 0.82955343 },
		{ "params": [0.0, 5.0], "expected": 0.50000000 },
		{ "params": [2.0, 3.0], "expected": 0.93033702 },
	],
	"f_cdf": [  # Generated using: stats.f.cdf(x, dfn, dfd)
		{ "params": [1.5, 2.0, 2.0], "expected": 0.60000000 },
		{ "params": [2.0, 5.0, 10.0], "expected": 0.83580505 },
		{ "params": [0.8, 3.0, 7.0], "expected": 0.46790173 },
	],
}