# res://addons/godot-stat-math/tables/cdf_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"weibull_cdf": [
		{ "params": [1.5, 1.0, 2.0], "expected": 0.89460078 },
		{ "params": [2.0, 2.0, 2.0], "expected": 0.63212056 },
		{ "params": [0.5, 1.0, 1.0], "expected": 0.39346934 },
	],
	"gamma_cdf": [
		{ "params": [2.0, 2.0, 2.0], "expected": 0.26424112 },
		{ "params": [1.0, 1.0, 1.0], "expected": 0.63212056 },
		{ "params": [3.0, 2.5, 1.5], "expected": 0.45058405 },
	],
	"t_cdf": [
		{ "params": [1.0, 10.0], "expected": 0.82955343 },
		{ "params": [0.0, 5.0], "expected": 0.50000000 },
		{ "params": [2.0, 3.0], "expected": 0.93033702 },
	],
	"f_cdf": [
		{ "params": [1.5, 2.0, 2.0], "expected": 0.60000000 },
		{ "params": [2.0, 5.0, 10.0], "expected": 0.83580505 },
		{ "params": [0.8, 3.0, 7.0], "expected": 0.46790173 },
	],
}