# res://addons/godot-stat-math/tables/error_functions_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"erf": [
		{ "params": [0.5], "expected": 0.52049988 },
		{ "params": [1.0], "expected": 0.84270079 },
		{ "params": [2.0], "expected": 0.99532227 },
	],
	"erfc": [
		{ "params": [0.5], "expected": 0.47950012 },
		{ "params": [1.0], "expected": 0.15729921 },
		{ "params": [2.0], "expected": 0.00467773 },
	],
	"erf_inv": [
		{ "params": [0.5], "expected": 0.47693628 },
		{ "params": [0.8], "expected": 0.90619380 },
		{ "params": [-0.3], "expected": -0.27246271 },
	],
	"erfc_inv": [
		{ "params": [0.5], "expected": 0.47693628 },
		{ "params": [1.5], "expected": -0.47693628 },
		{ "params": [0.2], "expected": 0.90619380 },
	],
}