# res://addons/godot-stat-math/tables/helper_functions_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"binomial_coefficient": [  # Generated using: special.comb(n, r, exact=True)
		{ "params": [5, 2], "expected": 10.00000000 },
		{ "params": [10, 3], "expected": 120.00000000 },
		{ "params": [7, 0], "expected": 1.00000000 },
		{ "params": [6, 6], "expected": 1.00000000 },
	],
	"log_factorial": [  # Generated using: special.gammaln(n+1)
		{ "params": [0], "expected": 0.00000000 },
		{ "params": [5], "expected": 4.78749174 },
		{ "params": [10], "expected": 15.10441257 },
	],
	"log_binomial_coef": [  # Generated using: np.log(special.comb(n, k, exact=True))
		{ "params": [5, 2], "expected": 2.30258509 },
		{ "params": [10, 3], "expected": 4.78749174 },
		{ "params": [7, 0], "expected": 0.00000000 },
	],
	"lower_incomplete_gamma_regularized": [  # Generated using: special.gammainc(a, z)
		{ "params": [2.5, 3.5], "expected": 0.77935969 },
		{ "params": [1.0, 2.0], "expected": 0.86466472 },
		{ "params": [3.0, 1.5], "expected": 0.19115317 },
	],
	"incomplete_beta": [  # Generated using: special.betainc(a, b, x)
		{ "params": [0.5, 2.0, 3.0], "expected": 0.68750000 },
		{ "params": [0.3, 1.5, 2.5], "expected": 0.41568785 },
		{ "params": [0.7, 3.0, 2.0], "expected": 0.65170000 },
	],
	"beta_function": [  # Generated using: special.beta(a, b)
		{ "params": [2.0, 3.0], "expected": 0.08333333 },
		{ "params": [1.5, 2.5], "expected": 0.19634954 },
		{ "params": [4.0, 1.0], "expected": 0.25000000 },
	],
}