# res://addons/godot-stat-math/tables/helper_functions_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"lower_incomplete_gamma_regularized": [
		{ "params": [2.5, 3.5], "expected": 0.77935969 },
		{ "params": [1.0, 2.0], "expected": 0.86466472 },
		{ "params": [3.0, 1.5], "expected": 0.19115317 },
	],
	"incomplete_beta": [
		{ "params": [0.5, 2.0, 3.0], "expected": 0.68750000 },
		{ "params": [0.3, 1.5, 2.5], "expected": 0.41568785 },
		{ "params": [0.7, 3.0, 2.0], "expected": 0.65170000 },
	],
	"beta_function": [
		{ "params": [2.0, 3.0], "expected": 0.08333333 },
		{ "params": [1.5, 2.5], "expected": 0.19634954 },
		{ "params": [4.0, 1.0], "expected": 0.25000000 },
	],
}