# res://addons/godot-stat-math/tables/helper_functions_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY
# Generated with: scipy 1.15.3, numpy 2.3.0

const VALUES: Dictionary = {
	"gamma_function": [  # Generated using: # scipy function call not documented
		{ "params": [1.0], "expected": 1.00000000 },
		{ "params": [2.0], "expected": 1.00000000 },
		{ "params": [3.0], "expected": 2.00000000 },
		{ "params": [4.0], "expected": 6.00000000 },
		{ "params": [5.0], "expected": 24.00000000 },
		{ "params": [0.5], "expected": 1.77245385 },
		{ "params": [1.5], "expected": 0.88622693 },
		{ "params": [2.5], "expected": 1.32934039 },
		{ "params": [0.1], "expected": 9.51350770 },
		{ "params": [10.0], "expected": 362880.00000000 },
	],
	"log_gamma": [  # Generated using: # scipy function call not documented
		{ "params": [1.0], "expected": 0.00000000 },
		{ "params": [2.0], "expected": 0.00000000 },
		{ "params": [3.0], "expected": 0.69314718 },
		{ "params": [4.0], "expected": 1.79175947 },
		{ "params": [5.0], "expected": 3.17805383 },
		{ "params": [0.5], "expected": 0.57236494 },
		{ "params": [1.5], "expected": -0.12078224 },
		{ "params": [2.5], "expected": 0.28468287 },
		{ "params": [10.0], "expected": 12.80182748 },
		{ "params": [100.0], "expected": 359.13420537 },
	],
	"binomial_coefficient": [  # Generated using: special.comb(n, r, exact=True)
		{ "params": [5, 2], "expected": 10.00000000 },
		{ "params": [10, 3], "expected": 120.00000000 },
		{ "params": [7, 0], "expected": 1.00000000 },
		{ "params": [6, 6], "expected": 1.00000000 },
	],
	"log_factorial": [  # Generated using: special.gammaln(n+1)
		{ "params": [0], "expected": 0.00000000 },
		{ "params": [5], "expected": 4.78749174 },
		{ "params": [10], "expected": 15.10441257 },
	],
	"log_binomial_coef": [  # Generated using: np.log(special.comb(n, k, exact=True))
		{ "params": [5, 2], "expected": 2.30258509 },
		{ "params": [10, 3], "expected": 4.78749174 },
		{ "params": [7, 0], "expected": 0.00000000 },
	],
	"lower_incomplete_gamma_regularized": [  # Generated using: special.gammainc(a, z)
		{ "params": [2.5, 3.5], "expected": 0.77935969 },
		{ "params": [1.0, 2.0], "expected": 0.86466472 },
		{ "params": [3.0, 1.5], "expected": 0.19115317 },
	],
	"incomplete_beta": [  # Generated using: special.betainc(a, b, x)
		{ "params": [0.5, 2.0, 3.0], "expected": 0.68750000 },
		{ "params": [0.3, 1.5, 2.5], "expected": 0.41568785 },
		{ "params": [0.7, 3.0, 2.0], "expected": 0.65170000 },
	],
	"beta_function": [  # Generated using: special.beta(a, b)
		{ "params": [2.0, 3.0], "expected": 0.08333333 },
		{ "params": [1.5, 2.5], "expected": 0.19634954 },
		{ "params": [4.0, 1.0], "expected": 0.25000000 },
	],
}