# res://addons/godot-stat-math/tables/pmf_pdf_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY
# Generated with: scipy 1.15.3, numpy 2.3.0

const VALUES: Dictionary = {
	"binomial_pmf": [  # Generated using: stats.binom.pmf(k, n, p)
		{ "params": [2, 5, 0.5], "expected": 0.31250000 },
		{ "params": [0, 5, 0.5], "expected": 0.03125000 },
		{ "params": [5, 5, 0.5], "expected": 0.03125000 },
		{ "params": [6, 5, 0.5], "expected": 0.00000000 },
		{ "params": [0, 5, 0.0], "expected": 1.00000000 },
		{ "params": [5, 5, 1.0], "expected": 1.00000000 },
	],
	"poisson_pmf": [  # Generated using: stats.poisson.pmf(k, lambda)
		{ "params": [2, 3.0], "expected": 0.22404181 },
		{ "params": [0, 3.0], "expected": 0.04978707 },
		{ "params": [0, 0.0], "expected": 1.00000000 },
		{ "params": [-1, 3.0], "expected": 0.00000000 },
	],
	"negative_binomial_pmf": [  # Generated using: stats.nbinom.pmf(k-r, r, p)
		{ "params": [5, 2, 0.5], "expected": 0.12500000 },
		{ "params": [2, 2, 0.5], "expected": 0.25000000 },
		{ "params": [1, 2, 0.5], "expected": 0.00000000 },
		{ "params": [2, 2, 1.0], "expected": 1.00000000 },
	],
	"normal_pdf": [  # Generated using: stats.norm.pdf(x, mu, sigma)
		{ "params": [0.0, 0.0, 1.0], "expected": 0.39894228 },
		{ "params": [1.0, 0.0, 1.0], "expected": 0.24197072 },
		{ "params": [2.0, 2.0, 1.0], "expected": 0.39894228 },
		{ "params": [5.0, 3.0, 2.0], "expected": 0.12098536 },
	],
	"exponential_pdf": [  # Generated using: stats.expon.pdf(x, scale=1/lambda)
		{ "params": [0.0, 1.0], "expected": 1.00000000 },
		{ "params": [1.0, 1.0], "expected": 0.36787944 },
		{ "params": [0.0, 2.0], "expected": 2.00000000 },
		{ "params": [2.0, 0.5], "expected": 0.18393972 },
		{ "params": [-1.0, 1.0], "expected": 0.00000000 },
	],
	"uniform_pdf": [  # Generated using: stats.uniform.pdf(x, a, b-a)
		{ "params": [2.5, 1.0, 4.0], "expected": 0.33333333 },
		{ "params": [1.0, 1.0, 4.0], "expected": 0.33333333 },
		{ "params": [4.0, 1.0, 4.0], "expected": 0.33333333 },
		{ "params": [0.5, 1.0, 4.0], "expected": 0.00000000 },
		{ "params": [4.5, 1.0, 4.0], "expected": 0.00000000 },
		{ "params": [0.0, -2.0, 2.0], "expected": 0.25000000 },
	],
	"gamma_pdf": [  # Generated using: stats.gamma.pdf(x, shape, scale=scale)
		{ "params": [1.0, 2.0, 1.0], "expected": 0.36787944 },
		{ "params": [0.0, 2.0, 1.0], "expected": 0.00000000 },
		{ "params": [-1.0, 2.0, 1.0], "expected": 0.00000000 },
	],
	"geometric_pmf": [  # Generated using: stats.geom.pmf(k, p)
		{ "params": [2, 0.5], "expected": 0.25000000 },
		{ "params": [1, 0.3], "expected": 0.30000000 },
		{ "params": [5, 0.1], "expected": 0.06561000 },
	],
	"lognormal_pdf": [  # Generated using: stats.lognorm.pdf(x, s=sigma, scale=exp(mu))
		{ "params": [1.0, 0.0, 1.0], "expected": 0.39894228 },
		{ "params": [2.0, 0.0, 0.5], "expected": 0.15261383 },
		{ "params": [0.5, 1.0, 0.2], "expected": 0.00000000 },
	],
	"weibull_pdf": [  # Generated using: stats.weibull_min.pdf(x, c=shape, scale=scale)
		{ "params": [1.0, 1.0, 1.0], "expected": 0.36787944 },
		{ "params": [1.5, 1.0, 2.0], "expected": 0.31619767 },
		{ "params": [2.0, 2.0, 3.0], "expected": 0.55181916 },
	],
	"f_pdf": [  # Generated using: stats.f.pdf(x, dfn, dfd)
		{ "params": [1.0, 2.0, 3.0], "expected": 0.27885480 },
		{ "params": [2.5, 5.0, 10.0], "expected": 0.09359475 },
		{ "params": [0.8, 10.0, 5.0], "expected": 0.59360177 },
	],
	"students_t_pdf": [  # Generated using: stats.t.pdf(x, df)
		{ "params": [0.0, 1.0], "expected": 0.31830989 },
		{ "params": [1.0, 2.0], "expected": 0.19245009 },
		{ "params": [2.0, 5.0], "expected": 0.06509031 },
		{ "params": [0.5, 30.0], "expected": 0.34787858 },
	],
	"beta_pdf": [  # Generated using: stats.beta.pdf(x, alpha, beta)
		{ "params": [0.5, 1.0, 1.0], "expected": 1.00000000 },
		{ "params": [0.3, 2.0, 5.0], "expected": 2.16090000 },
		{ "params": [0.7, 5.0, 2.0], "expected": 2.16090000 },
		{ "params": [0.5, 0.5, 0.5], "expected": 0.63661977 },
		{ "params": [0.5, 2.0, 2.0], "expected": 1.50000000 },
	],
	"chi_squared_pdf": [  # Generated using: stats.chi2.pdf(x, df)
		{ "params": [1.0, 1.0], "expected": 0.24197072 },
		{ "params": [2.0, 2.0], "expected": 0.18393972 },
		{ "params": [5.0, 4.0], "expected": 0.10260625 },
		{ "params": [10.0, 10.0], "expected": 0.08773368 },
	],
}
