# res://addons/godot-stat-math/tables/pmf_pdf_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY
class_name PmfPdfTestData
    
const VALUES: Dictionary = {
\t"geometric_pmf": [
\t\t{ "params": [2, 0.5], "expected": 0.25000000 },
\t\t{ "params": [1, 0.3], "expected": 0.30000000 },
\t\t{ "params": [5, 0.1], "expected": 0.06561000 },
\t],
\t"lognormal_pdf": [
\t\t{ "params": [1.0, 0.0, 1.0], "expected": 0.39894228 },
\t\t{ "params": [2.0, 0.0, 0.5], "expected": 0.15261383 },
\t\t{ "params": [0.5, 1.0, 0.2], "expected": 0.00000000 },
\t],
\t"weibull_pdf": [
\t\t{ "params": [1.0, 1.0, 1.0], "expected": 0.36787944 },
\t\t{ "params": [1.5, 2.0, 1.0], "expected": 0.31619767 },
\t\t{ "params": [2.0, 3.0, 2.0], "expected": 0.55181916 },
\t],
\t"f_pdf": [
\t\t{ "params": [1.0, 2.0, 3.0], "expected": 0.27885480 },
\t\t{ "params": [2.5, 5.0, 10.0], "expected": 0.09359475 },
\t\t{ "params": [0.8, 10.0, 5.0], "expected": 0.59360177 },
\t],
}
