# res://addons/godot-stat-math/tables/pmf_pdf_test_data.gd
# THIS FILE IS AUTOGENERATED BY generate_test_data.py
# DO NOT EDIT MANUALLY

const VALUES: Dictionary = {
	"geometric_pmf": [
		{ "params": [2, 0.5], "expected": 0.25000000 },
		{ "params": [1, 0.3], "expected": 0.30000000 },
		{ "params": [5, 0.1], "expected": 0.06561000 },
	],
	"lognormal_pdf": [
		{ "params": [1.0, 0.0, 1.0], "expected": 0.39894228 },
		{ "params": [2.0, 0.0, 0.5], "expected": 0.15261383 },
		{ "params": [0.5, 1.0, 0.2], "expected": 0.00000000 },
	],
	"weibull_pdf": [
		{ "params": [1.0, 1.0, 1.0], "expected": 0.36787944 },
		{ "params": [1.5, 1.0, 2.0], "expected": 0.31619767 },
		{ "params": [2.0, 2.0, 3.0], "expected": 0.55181916 },
	],
	"f_pdf": [
		{ "params": [1.0, 2.0, 3.0], "expected": 0.27885480 },
		{ "params": [2.5, 5.0, 10.0], "expected": 0.09359475 },
		{ "params": [0.8, 10.0, 5.0], "expected": 0.59360177 },
	],
	"students_t_pdf": [
		{ "params": [0.0, 1.0], "expected": 0.31830989 },
		{ "params": [1.0, 2.0], "expected": 0.19245009 },
		{ "params": [2.0, 5.0], "expected": 0.06509031 },
		{ "params": [0.5, 30.0], "expected": 0.34787858 },
	],
	"beta_pdf": [
		{ "params": [0.5, 1.0, 1.0], "expected": 1.00000000 },
		{ "params": [0.3, 2.0, 5.0], "expected": 2.16090000 },
		{ "params": [0.7, 5.0, 2.0], "expected": 2.16090000 },
		{ "params": [0.5, 0.5, 0.5], "expected": 0.63661977 },
		{ "params": [0.5, 2.0, 2.0], "expected": 1.50000000 },
	],
	"chi_squared_pdf": [
		{ "params": [1.0, 1.0], "expected": 0.24197072 },
		{ "params": [2.0, 2.0], "expected": 0.18393972 },
		{ "params": [5.0, 4.0], "expected": 0.10260625 },
		{ "params": [10.0, 10.0], "expected": 0.08773368 },
	],
}